version: "3.7"

services:
  nano-work-server:
    build: ./nano-work-server
    image: nano-work-server
    command: -c 4 -l 0.0.0.0:7000
    
  boompow-client:
    build: ./boompow-client
    image: boompow-client
    command: --limit-logging --async_mode --payout ban_3se931ts5w1xmn988jeztyz8nh35nfp6bwc33xgxom3hib8cex4zxhsom9fz --worker_uri nano-work-server:7000