version: "3.3"

services:
  nano-work-server:
    build: ./nano-work-server
    image: nano-work-server
    command: -c 4 -l 0.0.0.0:7000
    
  boompow-client:
    build: ./boompow-client
    image: boompow-client
    command: --limit-logging --async_mode --payout ban_193sufow93wj8unsuzeperm71ap1xem7fgjeo987uhjbtyi758mpdknzq9xi --worker_uri nano-work-server:7000
    
  dpow-client:
    build: ./dpow-client
    image: dpow-client
    depends_on:
      - nano-work-server
    command: --payout nano_193sufow93wj8unsuzeperm71ap1xem7fgjeo987uhjbtyi758mpdknzq9xi --worker_uri nano-work-server:7000